// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { InstructionDetail } from "./InstructionDetail";

export type BlockDetail = { ip: string, instrs: Array<InstructionDetail>, };
