// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BlockDetail } from "./BlockDetail";
import type { Var } from "./Var";

export type FunctionDetail = { ip: string, name: string | null, desc: string | null, details: string | null, xrefs: Array<string> | null, params: Array<Var> | null, ret: Var | null, blocks: Array<BlockDetail>, };
