// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type InstructionDetail = { ip: string, text: string, comment: string | null, label: string | null, jmp: string | null, };
