// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MemoryEntry } from "./MemoryEntry";

export type MemoryDetail = { entries: Array<MemoryEntry>, };
