// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FunctionOverview } from "./FunctionOverview";

export type MemoryAddressDetail = { addr: string, name: string, desc: string, typ: string, functions: Array<FunctionOverview>, };
