// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EXE } from "./EXE";
import type { FunctionOverview } from "./FunctionOverview";

export type Overview = { project_path: string, mem_size: number, exe: EXE, functions: Array<FunctionOverview>, };
