// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Var = { 
/**
 * an identifier name for the variable within the function
 */
name: string, 
/**
 * the parameter's value, either a register or an stack offset like [sp+4]
 */
value: string, 
/**
 * value type as expressed in Rust, e.g. u32 or CStr
 */
type: string, 
/**
 * human-readable description
 */
desc: string, };
