// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Display name and target IP; an empty IP denotes a non-function reference.
 */
export type XRefDetail = [string, string];
