name = "toupper_string"
desc = "Converts an ASCII string of length CX pointed to by DI to uppercase in-place."
ip = "0823:0b54"

---
; Save registers
0823:0b54 push di
0823:0b55 push cx

; Read character from string and check if it is within 'a'-'z'
0823:0b56 mov al,[di]
0823:0b58 cmp al,61h
@jmp '4
0823:0b5a jb short 0B62h

0823:0b5c cmp al,7Ah
@jmp '4
0823:0b5e ja short 0B62h

; Convert lowercase ASCII character to uppercase
0823:0b60 and al,5Fh

; Store character back, advance pointer, and repeat for CX characters
0823:0b62 mov [di],al
0823:0b64 inc di
@jmp '1
0823:0b65 loop 0B56h

; Restore registers and return
0823:0b67 pop cx
0823:0b68 pop di
0823:0b69 ret

